Repository jekyll/jekyll-watch, pull requests merged in 2018-10, with the labels that each got.

#73 Replace non-existent local variable
  lib/jekyll/watcher.rb
Labels: fix

#77 Initialize AppVeyor CI to test plugin on Windows
  README.md
  appveyor.yml
Labels: tests, windows

#78 Fix watcher failure due to incorrect file name encoding
  lib/jekyll/watcher.rb
  spec/test-sité/_posts/2014-08-08-歡迎使用jekyll.markdown
Labels: bug, fix, needs-tests
